In [14]:
import os
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense


In [15]:
import os
import pandas as pd
from PIL import Image
import numpy as np

# dataset
data_dir = 'sight_insight_dataset'

# Load CSV file containing image filenames and labels
train_df = pd.read_csv(os.path.join(data_dir, 'train.csv'))

# Initialize variables
img_height = 224
img_width = 224

# Function to load and preprocess image
def load_image(file_path):
    img = Image.open(file_path)
    img = img.resize((img_height, img_width))
    img_array = np.array(img) / 255.0  # Normalize pixel values
    return img_array

# Load and preprocess images and labels
X = [] 
y = train_df['diagnosis'].values

for filename, label in zip(train_df['id_code'], train_df['diagnosis']):
    subfolder = ['No_DR', 'Mild', 'Moderate', 'Severe', 'Proliferate_DR'][label]  # folder names of label
    file_path = os.path.join(data_dir, 'colored_images', subfolder, filename + '.png')
    img = load_image(file_path)
    X.append(img)

X = np.array(X) 


In [16]:
print(X)

[[[[0.17254902 0.0627451  0.00784314]
   [0.17647059 0.0627451  0.01176471]
   [0.18039216 0.0627451  0.01176471]
   ...
   [0.12941176 0.04705882 0.00784314]
   [0.11764706 0.04313725 0.00784314]
   [0.11372549 0.03921569 0.00784314]]

  [[0.18039216 0.0627451  0.01176471]
   [0.17647059 0.0627451  0.01176471]
   [0.18039216 0.06666667 0.01176471]
   ...
   [0.1254902  0.05098039 0.00784314]
   [0.12941176 0.04705882 0.00784314]
   [0.12156863 0.04313725 0.00784314]]

  [[0.18039216 0.0627451  0.01176471]
   [0.18431373 0.07058824 0.01176471]
   [0.19215686 0.07058824 0.01568627]
   ...
   [0.1254902  0.05490196 0.00784314]
   [0.1254902  0.05098039 0.00784314]
   [0.12941176 0.04705882 0.00784314]]

  ...

  [[0.15294118 0.06666667 0.01176471]
   [0.15686275 0.06666667 0.01176471]
   [0.16078431 0.06666667 0.01176471]
   ...
   [0.0745098  0.03529412 0.00784314]
   [0.07058824 0.03137255 0.00784314]
   [0.06666667 0.03137255 0.00784314]]

  [[0.14901961 0.05882353 0.01176471]
   [0.1

In [17]:
print(y)

[2 4 1 ... 2 0 2]
[2 4 1 ... 2 0 2]


In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# setup the Convolutional Neural Networks Model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(img_height, img_width, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(512, activation='relu'),
    Dense(5, activation='softmax')  
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Training
history = model.fit(X, y, epochs=10, batch_size=32, validation_split=0.2)


C:\Users\Hasha\PycharmProjects\datascience_assign\venv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 127s 1s/step - accuracy: 0.4527 - loss: 1.2786 - val_accuracy: 0.5825 - val_loss: 1.0957
Epoch 2/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 92s 1s/step - accuracy: 0.5446 - loss: 1.1200 - val_accuracy: 0.6712 - val_loss: 1.0020
Epoch 3/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 68s 737ms/step - accuracy: 0.6233 - loss: 1.0115 - val_accuracy: 0.6917 - val_loss: 0.8948
Epoch 4/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 74s 798ms/step - accuracy: 0.6557 - loss: 0.9067 - val_accuracy: 0.7108 - val_loss: 0.8523
Epoch 5/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 80s 871ms/step - accuracy: 0.7094 - loss: 0.8110 - val_accuracy: 0.7108 - val_loss: 0.8793
Epoch 6/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 100s 1s/step - accuracy: 0.6971 - loss: 0.8167 - val_accuracy: 0.7108 - val_loss: 0.8033
Epoch 7/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 104s 1s/step - accuracy: 0.7073 - loss: 0.7657 - val_accuracy: 0.6944 - val_loss: 0.8340
Epoch 8/10
92/92 ━━━━━━━━━━━━━━━━━━━━ 93s 999ms/step - accuracy: 0.7253 - loss: 0.7324 - val_accuracy: 0.7

C:\Users\Hasha\PycharmProjects\datascience_assign\venv\lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


In [13]:
model.save("identifier_model.h5")
